### ISSUE TITLE
Invalid calls to wrapped setTimeout on IE7 and IE8

### ISSUE THREAD

**Issue by DerGernTod** [taylorhakes/promise-polyfill#118] opened 2020-08-19 11:17 UTC
By accessing `setTimeout` instead of `window.setTimeout` on IE 7 and IE 8, a copy of the function is created. If later on the `window.setTimeout` function is wrapped by code on the website, this wrapper is not used anywhere because of the initial copy. This is a pretty stupid example of IE weirdness, details can be found here: http://www.adequatelygood.com/Replacing-setTimeout-Globally.html

Easiest fix: use `window.setTimeout` instead of `setTimeout`.

**Comment by kamtschatka** [comment] 2020-08-19 11:40
I have created a reproducer for it(see attached files)
Basically what we are doing: 
We have the promise-polyfill on the page and then we override window.setTimeout with our own wrapper. That worked fine until we added the promise-polyfill on all browsers we are testing, but is failing on IE7 and IE8 since we added the polyfill.

This is a very simplified reproducer, where i have included the original promise polyfill:
```
    <script src="promiseOriginal.js" type="text/javascript"></script>
    <script type="text/javascript">
		var originalSetTimeout = window.setTimeout;
		window.setTimeout = function(func, timeout) {
			console.log("wrapper called!");
			originalSetTimeout(func, timeout);
		};
		setTimeout(function () {
			console.log("function called");
		}, 100);
    </script>
```

Usually we see the output
```
wrapper called!
function called
```

But on IE7/IE8(also reproducible on IE11 in compatibility mode for these browsers) we only get 

```
function called
```

The reason is described in the link Gernot has already posted above: http://www.adequatelygood.com/Replacing-setTimeout-Globally.html
In the attached zip file I have also attached a fixed version, where the polyfill does not access `setTimeout`, but `window.setTimeout`, which fixes this problem.

Reproducer, if you are interested to try it yourself:
[promise.zip](https://github.com/taylorhakes/promise-polyfill/files/5096126/promise.zip)

**Comment by djleonskennedy** [comment] 2020-08-29 18:59
@DerGernTod @kamtschatka **IE7** and **IE8** are you serious guys ? :)

**Comment by kamtschatka** [comment] 2020-08-29 19:59
We are. And this library claims to support IE8+, so it absolutely makes sense to not break anything else in the process of providing a promise polyfill.

**Comment by taylorhakes** [comment] 2020-09-01 20:20
@DerGernTod @kamtschatka Thanks for the bug report. 

I have a comment explaining why this is necessary. https://github.com/taylorhakes/promise-polyfill/blob/master/src/index.js#L3 . This polyfill has been around for about 6 years and I haven't received this issue before (I personally used it on IE8 when I supported it). `setTimeout` is an implementation detail of this promise library, so I wouldn't expect overriding setTimeout to affect this code. Real promises do not use `setTimeout`.
```
wrapper called!
function called
``

If you would like to log when promises resolve (or change the behavior of the promise library), I recommend using the following API.

```
import Promise from 'promise-polyfill/src/polyfill';
Promise._immediateFn = window.setTimeout;
```

**Comment by kamtschatka** [comment] 2020-09-01 21:00
We just provided a reproducer issue, we do not really want to log when promises resolve.
We have a piece of code that overrides the setTimeout function, but this is broken, when we are using the promise polyfill on the same page(and it initializes before we override the setTimeout function)
We have created a workaround in our code for now, but we would rather have the proper fix in the promise-polyfill, so we can get rid of the workaround and other users of the polyfill will not run into the same problem.

**Comment by taylorhakes** [comment] 2020-09-03 20:02
@kamtschatka I provided the correct fix above. Overriding setTimeout globally and assuming it should affect `promise-polyfill` is not a supported use case of this library. If you want to adjust the immediate function, please use the code below.
```
import Promise from 'promise-polyfill/src/polyfill';
Promise._immediateFn = window.setTimeout;
```

**Comment by kamtschatka** [comment] 2020-09-03 20:11
No it is not the correct fix. We do not want to override setTimeout and have it affect the promise polyfill. We want to override the setTimeout function globally after the promise polyfill has initialized and have it affect the rest of the page, but due to a bug/quirk in IE this is not possible, because the way the promise polyfill access setTimeout creates a duplicate of setTimeout that makes that impossible.
Please try my example I have provided in my first post to see the problem.

**Comment by taylorhakes** [comment] 2020-09-03 22:12
@kamtschatka I understand your issue and tried your example. I don't see it as IE having a bug here. You are relying on an implementation detail of this polyfill library. Promises don't use setTimeout by default so changing setTimeout or window.setTimeout in any way should have no affect on promises. This library happens to use setTimeout, but that is an implementation detail (https://stackoverflow.com/questions/1777719/what-is-the-definition-of-an-implementation-detail). Your code will break if you rely on that because I have no intention to support that use case. I created an official API to update the immediate function, which is the only valid way of updating the immediateFn I will support.

**Comment by kamtschatka** [comment] 2020-09-04 05:31
No you do not understand. It is definitely IE having a bug here.
I don't care if the promise-polyfill uses setTimeout or not. In fact the whole implementation of the promise polyfill does not matter in the slightest. The library could be anything(as you can see the sample doesn't even use promises or anything related to the promise-polyfill, we just included it in the page and that causes sideeffects to the code), the problem is that the promise-polyfill accesses setTimeout instead of window.setTimeout, which creates a cached copy on IE and makes it impossible to override it later. And to clarify once again: We do not want to influence the promise-polyfill in any way with our setTimeout wrapper. The wrapper has been created for an entirely different purpose, but it stops working on IE7/8, when the promise-polyfill is active on the page, even if you never use the promise-polyfill at all.

**Comment by taylorhakes** [comment] 2022-03-12 22:55
Closing in favor using `Promise._immediateFn = (fn) => window.setTimeout(fn, 0);` You have full control over the immediate function. If you want to change the immediate function or how setTimeout is used, you can modify it there. You don't need to modify this polyfill

**Closed by taylorhakes** 2022-03-12 22:55 UTC

**Comment by kamtschatka** [comment] 2022-03-13 12:36
OK, I have tried to explain it multiple times now, but you seem to either not get it or choose to understand it. We have made our peace with it, but in case anyone else ever runs into this problem, have a look at the attached PR #119 to find the real fix.

**Comment by taylorhakes** [comment] 2022-03-13 18:11
@kamtschatka The code you provided, even if the correct fix is a very naive way to get the global object that doesn't work in all environments. See this post https://mathiasbynens.be/notes/globalthis . I don't want to update this library to add the correct globalThis code to support this use case. I am very sorry about that. There are workarounds described in the post you linked.  http://www.adequatelygood.com/Replacing-setTimeout-Globally.html . Just add your custom code before this library initializes
