### ISSUE TITLE
resolve() with a promise as argument has issue

### ISSUE THREAD

**Issue by keven425** [taylorhakes/promise-polyfill#18] opened 2016-03-05 04:53 UTC
Hi, I'm trying to use this library on IE11. resolve with a promise as argument doesn't pass in argument in the .then() function. Is this a bug?

```
var promise = new Promise(function (resolve, reject) {
    resolve('result');
});

var promise2 = new Promise(function (resolve, reject) {
    resolve(promise);
});

promise2.then(function(result) {
    // result is undefined
});
```

**Comment by taylorhakes** [comment] 2016-03-05 22:41
@keven425 I am unable to reproduce your issue in IE11.

I created a JSBin with your code above. http://jsbin.com/fovebecuqi/edit?html,js,console,output
`result` is logged in my console. Are you seeing something different?

**Comment by taylorhakes** [comment] 2016-03-10 01:39
I am going to close this issue for now. Please respond if you feel there is still an issue.

**Closed by taylorhakes** 2016-03-10 01:39 UTC

**Comment by keven425** [comment] 2016-03-10 03:57
@taylorhakes thank you for the reply. Yes, I tried your jsbin in IE11, and it's working as intended. Thank you for verifying.

What confused me was that IE 11 debugger was not displaying request data reliably. Sorry for my late reply.
